# Generated by Django 3.1.2 on 2020-10-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
        ('jwt_auth', '0003_auto_20201021_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instrument',
            field=models.ManyToManyField(related_name='user', to='instruments.Instrument'),
        ),
    ]
