# Generated by Django 3.1.2 on 2020-10-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
        ('jwt_auth', '0004_user_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='instrument',
            field=models.ManyToManyField(blank=True, related_name='user', to='instruments.Instrument'),
        ),
    ]
