# Generated by Django 3.1.2 on 2020-10-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0005_auto_20201023_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='skill_level',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], default='1', max_length=12),
        ),
    ]
