# Generated by Django 3.1.2 on 2020-11-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0006_auto_20201025_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSsDFy7kDSzHSPQDGGUXymbffL0plCs496Etw&usqp=CAU', max_length=800),
        ),
        migrations.AlterField(
            model_name='user',
            name='skill_level',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], default='Beginner', max_length=12),
        ),
    ]
