# Generated by Django 3.1.2 on 2020-10-22 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bands', '0004_band_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='empty', max_length=20)),
                ('recipient', models.ManyToManyField(related_name='recipient', to=settings.AUTH_USER_MODEL)),
                ('related_band', models.ManyToManyField(related_name='band', to='bands.Band')),
            ],
        ),
    ]
