# Generated by Django 3.1.2 on 2020-10-22 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bands', '0004_band_owner'),
        ('chat', '0002_auto_20201022_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='participants',
        ),
        migrations.AddField(
            model_name='chat',
            name='sender',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='sent_chats', to='jwt_auth.user'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='chat',
            name='related_band',
        ),
        migrations.AddField(
            model_name='chat',
            name='related_band',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='bands.band'),
            preserve_default=False,
        ),
    ]
