# Generated by Django 3.1.2 on 2020-10-21 13:48

import django.core.validators
from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('goals', models.CharField(default='1', max_length=12)),
                ('size', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(2)])),
                ('city', models.CharField(max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
            ],
        ),
    ]
