# Generated by Django 3.1.2 on 2020-10-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='goals',
            field=models.CharField(choices=[('1', 'Make music'), ('2', 'Make money'), ('3', 'Make friends')], default='1', max_length=12),
        ),
    ]
