# Generated by Django 3.1.2 on 2020-10-21 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bands', '0003_auto_20201021_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='created_band', to='jwt_auth.user'),
            preserve_default=False,
        ),
    ]
