# Generated by Django 3.1.2 on 2020-10-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('bands', '0004_band_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='band', to='genres.Genre'),
        ),
        migrations.AlterField(
            model_name='band',
            name='goals',
            field=models.CharField(choices=[('Make music', 'Make music'), ('Make money', 'Make money'), ('Make friends', 'Make friends')], default='1', max_length=12),
        ),
    ]
